import matplotlib.pyplot as plt
import pandas as pd

def func711(seq):
    dct = {}
    for i in set(seq):
        dct[i] = seq.count(i)
    return dct

def func712(seq):
    dct = {}
    for i in set(seq):
        dct[i] = seq.count(i)

    labels, sizes = [], []

    for x, y in dct.items():
        labels.append(x)
        sizes.append(y)

    return labels, sizes

def func713(seq):
    geneticCode = {'TTT':'F', 'TTC':'F', 'TCT':'S', 'TCC':'S',
                'TAT':'Y', 'TAC':'Y', 'TGT':'C', 'TGC':'C',
                'TTA':'L', 'TCA':'S', 'TAA':None, 'TGA':None,
                'TTG':'L', 'TCG':'S', 'TAG':None, 'TGG':'W',
                'CTT':'L', 'CTC':'L', 'CCT':'P', 'CCC':'P',
                'CAT':'H', 'CAC':'H', 'CGT':'R', 'CGC':'R',
                'CTA':'L', 'CTG':'L', 'CCA':'P', 'CCG':'P',
                'CAA':'Q', 'CAG':'Q', 'CGA':'R', 'CGG':'R',
                'ATT':'I', 'ATC':'I', 'ACT':'T', 'ACC':'T',
                'AAT':'N', 'AAC':'N', 'AGT':'S', 'AGC':'S',
                'ATA':'I', 'ACA':'T', 'AAA':'K', 'AGA':'R',
                'ATG':'M', 'ACG':'T', 'AAG':'K', 'AGG':'R',
                'GTT':'V', 'GTC':'V', 'GCT':'A', 'GCC':'A',
                'GAT':'D', 'GAC':'D', 'GGT':'G', 'GGC':'G',
                'GTA':'V', 'GTG':'V', 'GCA':'A', 'GCG':'A',
                'GAA':'E', 'GAG':'E', 'GGA':'G', 'GGG':'G'}

    seq = seq[:len(seq)-len(seq) % 3]
    res = []
    for i in range(0, len(seq), 3):
        for key, _ in geneticCode.items():
            if key == seq[i:i+3]:
                res.append(key)
    dct2 = {}
    for i in set(res):
        dct2[i] = 0

    for i in res:
        dct2[i] += 1
    return dct2

def resfunc(seq):
    dctr = func711(seq)
    x, y = func712(seq)
    dct2 = func713(seq)
    fig, [(g1, g2), (g3, g4)] = plt.subplots(nrows=2, ncols=2, figsize=(20,12))
    g1.bar(dctr.keys(), dctr.values())
    g1.title.set_text("Nucleotide counts")
    g2.pie(y, labels=x)
    g2.axis('equal')
    g2.title.set_text("Nucleotide ratios")
    g3.bar(dct2.keys(), [i/sum(dct2.values()) for i in dct2.values()])
    g3.title.set_text("Codon frequencies")
    g4.boxplot([i/sum(dct2.values()) for i in dct2.values()])
    g4.set_xticklabels(["codons"])
    g4.title.set_text("Codon frequencies boxplot")
    fig.savefig('7.png')

resfunc('ATCCTGTATCGGAACATCAATTGTGCATCGGGCCAGCATAATCATGTCATCTGGGAAGTGGCCGTAGGATAAATAATTCAATAAAGATGTCGTTTTGCTAGTATACGTCTAGGCGTCACCCGCCATCTCTGTGCAGGTGGGCCGACGAGACATTGTCCCTGATTTCTCCACTACTAATAGCACACACGGGGCAATACCAGCACAAGCTAGTCTCGCGGGAACGCTCGTCAGCATACGAAAGAGCTTAAGGCACGCCAATTCGCACTGTCAGGGTCACTTGGGTGTTTTGCACTACCGTCAGGTACGCTAGTATGCGTTCTTCCTTCCAGAGGTATGTGGCTGCGTGGTCAAAAGTGCGGCATTCGTATTTGCTCCTCGTGTTTACTCTCACAAACTTGACCTGGAGATCAAGGAGATGCTTCTTGTGGAACTGGACAACGCATCAACGCAACGGATCTACGTTACAGCGTGCATAGTGAAAACGGAGTTGCTGACGACGAAAGCGACATTGGGATCTGTCTGTTGTCATTCGCGGAAAACATCCGTTCACGAGGCGGACACTGATTGACACGGTTTTGCAGAAGGTTAGGGGAATAGGTTAAATTGAGTGGCTTAAAAATGCTATGTCTGGGATTAAAGTGTAGTAAACTGTGATTAACGGAGACGGTTTTAAGACAGGAGTTCGCAAAATCAAGCGGGGTCATTACAACGGTTATTCCTGGTGGTTTAGGCGTACAATGTCCTGAAGAATATTTAAGAAAAAAGCACCCCTCGTCGCCTAGAATTACCTACCGCGGTCGACCATACCTTCGATTATCGCGCCCACTCTCCCATTAGTCGGCAGAGGTGGTTGTGTTGCGATAGCCCAGTATGATATTCTAAGGCGTTACGCTGATGAATATTCTACGGAATTGCCATAGGCGTTGAACGCTACACGGACGATACGAATTTATGTATAGAGCGGGTCATCGAAAGGTTATACTCTTGTAGTTAACATGTAGCCCGGCCCTATTAGTACAGCAGTGCCTTGAATGACATTCTCATTATTAAATTTTCTCTACAGCCAAACGACCAAGTGCATTTCCACGGAGCGCGATGGAGATTCATTCACTCGGCAGCTCTGTAATAGGGACTAAAAGAGTGATGATAATCATGAGTGCCGCGTTATGGTGGTGTCGGAACAGAGCGGTCTTACGGCCAGTCGTATTCCTTCTCGAGTTCCGTCCAGTTAAGCGTGACACTCCCAGTGTACCCGCAAACCGTGATGGCTGTGCTTGGAGTCAATCGCATGTAGGATGGTCTCCAGACACCGGGGCACCAGTTTTCACGCCCAAAGCATAAACGACGAGCAGTCATGAAAGTCTTAGAACTGGACGTGCCGTTTCTCTGCGAATAATACCTCGAGCTGTACCGTTGTTGCGCTGCCTAGATGCAGTGCTGCTCTTATCACATTTGCTTCGACGACTGCCGCCTTCGCTGTTTCCCTAGACACTCAACAATAAGCGCTTTTTGTAGGCAGGGGCACCCCCTATCAGTGGCTGCGCCAAAACATCTTCGGATCCCCTTGTCCAATCAAATTGATCGAATTCTTTCATTTAAGACCCTAATATGACATCATTAGTGATTAAATGCCACTCCCAAAATTCTGCCTAGAAATGTTTAAGTTCGCTCCACTAAAGTTGTTTAAAACGACTACTAAATCCGCGTGATAGGGGATTTCATATTTAATCTTTTATCGTAAGGAACAGCCGATCTTAATGGATGGCCGCAGGTGGTATGGAAGCTATAAGCGCGGGTGAGAGGGTAATTAGGCGTGTTCACCTACACTACGCTAACGGGCGATTCTATAAGATTGCACATTGCGTCTACTTATAAGATGTCTCAACGGCATGCGCAACTTGTGAAGTGCCTACTATCCTTAAACGCATATCTCGCACAGTAACTCCCCAATATGTGAGCATCTGATGTTGCCCGGGCCGAGTTAGTCTTGTGCTCACGGAACTTATTGTATGAGTAGTGATTTGAAAGAGTTGTCAGTTAGCTCGTTCAGGTAATGGTTCCTCACACTACGTCAAAATAAGAGAGCGGTCGTGACATTATCCGTGATTTTCTCACTACTATCAGTACTCACGACTCGATTCTGCCGCAGCCACGTATCGCCAGAAAGCCAGTCAGCATTAAGGAGTGCTCTGGGCAGGACAACTCGCATAGTGAGAGTTACATGTTCGTTGGGCTCTTCCGACACGAACCTCAGTTGGCCTACATCCTACCTGAGGTCTGTGCCCCGGTGGTGAGAAGTGCGCATTTCGTTCTTGCAGCTCGTCAGTACTTTCAGAATCATGGCCTGCACGGTAGAATGACGCTTATAATGGACTTCGACATGGCAATAACCCCCCGTTTCTACCTCAAGAGGAGAAAAGTATTAACATGACTGCTGTCGGCACAAGGGCCAAAGAAGTCTCCAATTTCTTATTCCCGAATAACATCCGTCTCCCTGCGGGAAAATCACCGACCGCATTTCATAGAAGCCTGGGGGAACAGATAGGTCTAATTAGCTTAAGAGAGTAAATCCTGGGATCATTCAGTAGTAACCACAAACTTACGCTGGGGCTTCTTTGGCGGATTTTTACAGATACTAACCAGGTGATTTGAAGTAAATTAGTTGAGGATTTAGCCGCGCTATCCGGTAATCTCCAAATTAAAACATACCGTTCCATGAGGGCTAGAATTACTTACCGGCCTTCACCATGCCTGCGCTATACGCGCCCACTCTCCCGTTTATCCGTCCAAGCGGATGCAATGCGATCCTCCGCTAAGATATTCTTACGTGTAACGTAGCTATGTATTTTACAGAGCTGGCGTACGCGTTGAACACTTCACAGATGATAGGGATTCGGGTAAAGAGCGTGTTATTGGGGACTTACACAGGCGTAGACTACAATGGGCCCAACTCAATCACAGCTCGAGCGCCTTGAATAACGTACTCATCTCTATACATTCTCGACAATCTATCGAGCGACTCGATTATCAACGGGTGTCTTGCAGTTCTAATCTCTTGCCAGCATCGTAATAGCCTCCAAGAGATTGATGATAGTCATGGGCACAGAGCTGAGACGGCGCCGATGGATAGCGGACTTTCGGTCAACCACAATTCCCCACGAGACAGGTCCTGCCGTGCGCATCACTCTGAATGTACAAGCAACCCAAGAGGGCTGAGCCTGGACTCAGCTGGTTCCTGGGTGAGCTCGAGACTCGGGGTGACAGCTCTTCATACATAGAGCGGGGGCGTCGAACGGTCGTGAAAGTCATAGTACCCCGGGTACCAACTTACTGAGGATATTGCTTGAAGCTGTACCGTTTTAGGGGGGGAACGCTGAAGATCTCTTCTTCTCATGACTGAACTCGCGAGGGTCGTGATGTCGGTTCCTTCAAAGGTTAAAGAACAAAGGCTTACTGTGCGCAGAGGAACGCCCATTTAGCGGCTGGCGTCTTGAATCCTCGGTCCCCCTTGTCTTTCCAGATTAATCCATTTCCCTCATTCACGAGCTTACCAAGTCAACATTGGTATATGAATGCGACCTTGAAGAGGCCGCTTAAAAATGGCAGTGGTTGATGCTCTAAACTCCATTTGGTTAACTCGTGTATCACCGCGATAGGCTGATAGAGGTTTAATATTGTATAGCAAGGTACTTCCGGTCTCAATGAATGGCCGGGAAAGGTACGCGCGCGGTATGGGAGGGTCAAGGGGCCAATAGAGAGGCTCCTCTCTCACTCGCTAGGAGGCAATTGTATAACAATGCTTACTGCATCGATACATAAAACGTGTCCATCGGTTGCCCAAACTGTGAAGTGTCTATCACCCCTAGGCCCGTTTCCCGCATATAAACGCCAGGTTGTATCCGCATTTGATGCTACCGTGGATGAGTCAGCGTCGAGCACGCGGCACTTATTGCATGAGTAGGGTTGACTAAGAGCCGTTAGATGCCTCGCTGTACTAATAGTTGTCGACAGATCGTCAAGATTAGAAAACGGTACCAGCATTTTCGGAGGTTCTCTAACTAGTATGGATAGCCGTGTCTTCACTGTGCTGCGGCTACCCATCGCCTGAAATCCAGTTGGTGTCAAGCCATCCCCTGTCCAGGACGCCGCATGTAGTGAAACATACACGTTGCTCGGGTTCACCCCGGTCCGTTCTGAGTCGACCAAGGACACAATCGAGCTCCGATCCGTACTGTCGAGAAACTTGTATCCGACCCCCGCAGCTTGCCAGCTCTTCGGGTATCATGGAGCCTATGGTTGAACGTGTCCGATAACGAACTTCGACATGATAAAGTCCCCCCCTCGCGACTACCAGAGAAGAAGACTACTGAGTTGAGCGTTCCCAGCACTTCAGCCAAGGAAGCTACCAATTTTTAGTTTCCGAGTGTCACGTCTGACCTCGCGGGTAGATTGCCGAGCGTAGAGCTTACGAGCCAGCGGAAACAGTAAGGCCTTTTTAAGTATGGGGAGTAAGTGATCGAACGCTTCAGATGTGACCATATACTTAGGCTGGATCTCGTCCCGTGAATTTTAACCCTCACCAACTACGAGATATGAGGTAAGCCAAAAAAGCACGTGGTGGCGCTCACCGACTGTTCCCAAACTGTAACTCATCGTTCCGTCAAGGCCTGACTTACTTCCCGGCCCTTTCCATGCGCGGACCATACCGTCCTAGTTCTTCGGTTATGTTTCCGATGTAGGAGTGAGCCTACCTCCGTTTGCGTCTTGTTACCAATGAAAAAGCTATGCACTTTGTACAGGGTGCCATCGGGTTTCTGAACTCTCAGATAGTGGGGATCCCGGGAAAGGGCCTATATTTGCGGTCCAACTTAGGCGTAAACCTCGATGCTACCTACTCAGACCCACCCCGCGCGGGGTAAATATGGCACTCATCCCAGCTGGTTCTTGGCGTTCTACGCAGCCACATGTTCATTAACAGTTGTCTGGTAGCACAAAAGTAT')
